[directory]
truncation_length = 0

[character]
symbol = "->"

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[python]
symbol = "î˜† "

[rust]
symbol = "ï€“ "

[git_status]
ahead    = "ï…¶"
behind   = "ï…µ"
deleted  = "ğŸ©"
diverged = "ï½"
